---
- name: Cleanup Docker and remove motra working directory
  hosts: all
  become: true
  vars_files:
    - vars/prod.yml

  roles:
    - role: motra_clean
      tags: motra_clean
    - role: motra
      tags: motra
