---
# Production overrides
# Most defaults are now in role defaults; use this file for environment-specific overrides only

# Example overrides (uncomment to use):
# scx_crates_to_install:
#   - scxctl
#   - scxtop
# motra_version: "v1.2.0"
# kernel_expected_version: "6.12.0-rc5-v8-16k+"

