---
- name: Run scheduler matrix on server only
  hosts: rpiserver
  become: true
  vars_files:
    - vars/prod.yml
  vars:
    sched_test_runs:
      - { scheduler: "scx_bpfland", attack: false, duration: 300 }
      - { scheduler: "scx_bpfland", attack: true, duration: 300 }
      - { scheduler: "scx_chaos", attack: true, duration: 300 }
      - { scheduler: "scx_p2dq", attack: false, duration: 300 }
      - { scheduler: "scx_rlfifo", attack: false, duration: 300 }
      - { scheduler: "scx_rustland", attack: false, duration: 300 }
      - { scheduler: "scx_simple", attack: false, duration: 300 }
      - { scheduler: "scx_qmap", attack: false, duration: 300 }
      - { scheduler: "scx_central", attack: false, duration: 300 }
      - { scheduler: "scx_nest", attack: false, duration: 300 }
      - { scheduler: "scx_bpfland", attack: false, duration: 300 }
      - { scheduler: "scx_bpfland", attack: true, duration: 300 }
      - { scheduler: "scx_chaos", attack: true, duration: 300 }
      - { scheduler: "scx_p2dq", attack: false, duration: 300 }
      - { scheduler: "scx_rlfifo", attack: false, duration: 300 }
      - { scheduler: "scx_rustland", attack: false, duration: 300 }
      - { scheduler: "scx_simple", attack: false, duration: 300 }
      - { scheduler: "scx_qmap", attack: false, duration: 300 }
      - { scheduler: "scx_central", attack: false, duration: 300 }
      - { scheduler: "scx_nest", attack: false, duration: 300 }
      - { scheduler: "scx_flatcg", attack: false, duration: 300 }
      - { scheduler: "scx_cosmos", attack: true, duration: 300 }
      - { scheduler: "scx_flash", attack: true, duration: 300 }
      - { scheduler: "scx_mitosis", attack: true, duration: 300 }
      - { scheduler: "scx_p2dq", attack: true, duration: 300 }
      - { scheduler: "scx_rlfifo", attack: true, duration: 300 }
      - { scheduler: "scx_rustland", attack: true, duration: 300 }
      - { scheduler: "cfs", attack: false, duration: 300 }
      - { scheduler: "scx_bpfland", attack: false, duration: 300 }
      - { scheduler: "scx_chaos", attack: false, duration: 300 }
      - { scheduler: "scx_cosmos", attack: false, duration: 300 }
      - { scheduler: "scx_flash", attack: false, duration: 300 }
      - { scheduler: "scx_mitosis", attack: false, duration: 300 }

  tasks:
    - name: Run paired passes sequentially per scheduler entry
      include_tasks: _scheduler_pair.yml
      vars:
        run: "{{ item }}"
      loop: "{{ sched_test_runs }}"

    - name: Cooldown between runs (server only)
      ansible.builtin.wait_for:
        timeout: 20
      when: "'rpiserver' in group_names"
